### ISSUE TITLE
Image Caption Not Appearing in GitHub

### ISSUE THREAD

**Issue by fdicera** [cfss-su20/hw01#26]
In my README.md file I have a caption written for my image, and when I preview the file in R the caption appears with the image. When I pushed the code, however, only the image appears on GitHub without any caption. I am not sure how to go about fixing this issue. Thanks in advance.

**Comment by bensoltoff** [comment]
On GitHub, the text is not rendered as an image caption. Instead it is treated as the **alternative text**. This is displayed if the image link is broken, or if someone who is visually-impaired uses a screen reader to read the contents of the page. This is normal behavior (sometimes RStudio and GitHub render the same Markdown formatting slightly differently).

**Comment by fdicera** [comment]
I see, thank you for the clarification.
