### ISSUE TITLE
Issue pushing changes to Github. 

### ISSUE THREAD

**Issue by manzoniUC** [cfss-su20/hw01#4]
Hi - I hope I've done this right and added an issue in the correct place for it. 
I've been working on HW01, and am consistently running into the same problem - my edits do not consistently get pushed to Github. I've watched the video tutorial on how to do this, so I'm confused as to why my edits are not consistently showing up on github. RStudio Server tells me that everything is up-to-date when I try to push changes, but it isn't.
I've been struggling with this for the past half hour, so I figured it was time to ask.
Thank you very much!

**Comment by bensoltoff** [comment]
What should the last line be in your readme?

**Comment by manzoniUC** [comment]
Hi Dr. Soltoff,
the last line in my README should be:
I play the double **bass** and electric **bass**. I also sing **bass** with the University of Chicago Glee Club - you can check out a video of us [here](https://www.youtube.com/watch?v=7OD1kwWEbuY), if you'd like. There's a lot of **bass** going on in that video.

**Comment by manzoniUC** [comment]
Closing this because after some serious fiddling, I discovered I needed to click the README file BOTH when I push the commit and push to GitHub through the tab on the right-hand side.
